apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: container
        image: image-registry.openshift-image-registry.svc:5000/sample/postgresql:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
            protocol: TCP
        env:
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_DATABASE
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_USERNAME
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
        command:
        - /bin/sh
        - -c
        - echo "Container UP." && psql -U $POSTGRESQL_USER -d $POSTGRESQL_DATABASE && tail -f /dev/null
      terminationGracePeriodSeconds: 0
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
