apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode
  template:
    metadata:
      labels:
        app: vscode
    spec:
      containers:
      - name: container
        image: docker.io/jefferyb/code-server:latest
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 0
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
