apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: container
        image: image-registry.openshift-image-registry.svc:5000/sample/postgresql:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5432
            protocol: TCP
        env:
          - name: POSTGRESQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: database-cm
                key: database
          - name: POSTGRESQL_USER
            valueFrom:
              configMapKeyRef:
                name: database-cm
                key: username
          - name: POSTGRESQL_PASSWORD
            value: "pswd"
      terminationGracePeriodSeconds: 0
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
