apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nginx-sample
spec:
  failedBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: nginx-sample:latest
  source:
    contextDir: /1.20/test/test-app
    git:
      uri: https://github.com/sclorg/nginx-container.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 1
