apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nginx-custom
spec:
  failedBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: nginx-custom:latest
  source:
    dockerfile: |
      FROM image-registry.openshift-image-registry.svc:5000/nginx-sample:latest

      RUN echo "Hello World" > /opt/app-root/src/index.html
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: nginx-sample:latest
        namespace: sample
    type: Docker
  successfulBuildsHistoryLimit: 1
