apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: postgresql-sample
spec:
  tags:
  - from:
      kind: DockerImage
      name: registry.redhat.io/rhel9/postgresql-15:latest
    name: latest
